### ISSUE TITLE
Feature Request: (Host current builds under "Releases")

### ISSUE THREAD

**Issue by Xeddius** [dubbadhar/gramophy#1]
Please host the current windows and eventually Linux/Mac builds under "Releases" tab since you can't post it on reddit.

**Comment by sakshatshinde** [comment]
If you are not sure how to do this checkout : https://help.github.com/en/github/administering-a-repository/creating-releases

**Comment by rnayabed** [comment]
I see. thanks! as soon as I make a difference stable version of this, ill create a GitHub release.

**Comment by rnayabed** [comment]
@Xeddius @sakshatshinde done. enjoy ;)

**Comment by rnayabed** [comment]
@Xeddius @sakshatshinde can you help me make JREs for Mac/Linux (If you have one machine that has it installed) ?

**Comment by sakshatshinde** [comment]
@dubbadhar I am not familiar with Java, but I do have a Linux machine. So if you could point me towards a resource/guide which I could use to make JREs for this project, would be happy to help!

**Comment by rnayabed** [comment]
@sakshatshinde dont worry, i was finally able to reinstall linux (popos) on my laptop and now i am working on a linux version.

**Comment by rnayabed** [comment]
@sakshatshinde Added Linux Support! Check it out!
